#!/usr/bin/env python
import sys
from matplotlib import pyplot as plt
import rosbag
bag = rosbag.Bag(sys.argv[1])
T = []
ACC_X = []
ACC_Y = []
ACC_Z = []
for topic, msg, t in bag.read_messages(topics=['/imu']):
    T.append(msg.header.stamp.to_sec())
    acc = msg.angular_velocity
    ACC_X.append(acc.x)
    ACC_Y.append(acc.y)
    ACC_Z.append(acc.z)
bag.close()
plt.plot(T, ACC_X)
plt.plot(T, ACC_Y)
plt.plot(T, ACC_Z)
plt.show()

