#!/usr/bin/env python
import sys
from matplotlib import pyplot as plt
import rosbag
bag = rosbag.Bag(sys.argv[1])
X = []
Y = []
for topic, msg, t in bag.read_messages(topics=['/gps/fix']):
    X.append(msg.longitude)
    Y.append(msg.latitude)
    print msg.latitude, msg.longitude
bag.close()
plt.scatter(X, Y)
plt.show()
