#!/bin/sh
rosbag record -o jr1_$1 /rosout /cmd_vel /imu /stereo/right/camera_info /stereo/right/image_raw /stereo/left/camera_info /stereo/left/image_raw /diagnostics /gps/time_reference /gps/fix /gps/vel /cmd_left /cmd_right

