#!/usr/bin/env python
import serial, sys, time

port = sys.argv[1]
baudrate = 9600
ser = serial.Serial(port, baudrate, timeout=0.1)
ser.flush()

# wait for arduino bootloader to finish
time.sleep(2.0)

message = 'rstuvwxyzabcdefghi'
for c in message:
    print 'Writing:', c
    ser.write(c)

    c = ser.read()
    if len(c) > 0:
        print 'Read:', c
